apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}-kafka
  description: kafka topic
spec:
  type: kafka-topic
  owner: ${{values.owner}}
  system: ${{values.application.split(":")[1]}}
  subcomponentOf: ${{values.kafka.split(":")]1]}}