name: push
on: 
  push:
    branches:
      - master
    tags:        
      - v*
    paths-ignore:
      - ".helm/**"

jobs:
  call-workflow:
    uses: mathianasj-backstage/workflows/.github/workflows/quarkus-ci-cd.yaml@master
    with:
      app: ${{values.application.split(":")[1]}}
      component: ${{values.component_id}}