{% for environment in values.environments.split(",") %}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${{values.application_id}}-${{environment}}
  namespace: ${{values.application_id}}-build
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ${{values.application_id}}-${{environment}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'

{% endfor %}